name: Build Extreme Math for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MinGW for Windows
      run: |
        choco install mingw

    - name: Compile with g++
      run: |
        g++ -std=c++11 -I./src/include -o build/extreme_math src/main.cpp src/logging.cpp src/equation.cpp src/tui.cpp

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: extreme-math-windows
        path: |
          extreme_math.exe
